# Generated by Django 5.0.6 on 2024-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0002_remove_contact_gridcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gridCheck',
            field=models.BooleanField(default=False),
        ),
    ]
