# Generated by Django 5.0.6 on 2024-05-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gridCheck',
        ),
    ]
