# Generated by Django 5.0.6 on 2024-05-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0006_remove_contact_gridcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('your_age', models.CharField(max_length=50)),
                ('your_profession', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
